server:
  port: 8090

spring:
  application:
    name: oauth2
  datasource:
    url: jdbc:h2:~/test
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
#      h2 사용 명시
  jpa:
    hibernate:
      ddl-auto: create # drop if exists and making entity
    properties:
      hibernate:
        #show_sql: true
        format_sql: true